config/routes.rb
Rails.application.routes.draw do
root "bands#index"

resources :bands
get "about", to: "bands#about"

resources :bands, only: [:new, :index]

end

app/models/band.rb
class Band < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @band = Band.order("RANDOM()").first
  end

def about
end

def new
  @band = Band.new
end

def create 
  Band.create(band_params)
  redirect_to root_path
end

private

def band_params
  params.require(:band).permit(:artist, :date, :location)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/about.html.erb
<div class="col-xs-10 col-xs-offset-1">
  <h1>About Krista</h1>

  <p>
    Krista is and avid concertgoer. When she's not studying how to write code, she is attending live shows all over the country. No concert is too far for her to travel.
  </p>
  <br />
  <p>
    Krista's first live show attendance was to see the Beastie Boys at Lollapalooza 1994. She has since gone on to see over 200 concerts during the following 20 years.
  </p>
  
  <div class="col-xs-12 col-sm-4">
  <br /><br />
  <%= image_tag "concert1.jpg", class: "img-responsive" %>
  </div>

</div>

app/views/bands/index.html.erb
    <h1><%= @band.artist %></h1><br />
    <i><%= @band.date %></i><br />
    <h5><%= @band.location %></h5><br />

app/views/bands/new.html.erb
<div class="col-xs-10 col-xs-offset-1">

<h1>Add New Show</h1>
  <%= simple_form_for @band do |f| %>
    <%= f.input :artist %>
    <%= f.input :date %>
    <%= f.input :location %>
    <br />
    <%= f.submit "Add", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Liveshows</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="col-xs-6 links">
      <%= link_to "Concert Guide: Krista's Review of the Best Live Shows", root_path %>
    </div>
    <div class="col-xs-8 col-xs-offset-1 col-sm-offset-0 col-sm-5 links">
      <%= link_to "Home", root_path %>
      &nbsp;&nbsp;
      <%= link_to new_band_path do %>
       <i class="glyphicon glyphicon-plus-sign"></i>
       Add Band
       <% end %>
       
       &nbsp;&nbsp;
      <%= link_to "About", about_path %>
    </div>
  </header>
  <hr />
  <br class="clear" />

<div class="container">
<%= yield %>
  </div>

  <div class="footer">
    <div class="container">
        <div class="col-xs-6 footer-blurb">
          <font color="white">Created by </font><a class="name" href="http://www.kristaleighdesign.com/">Krista &copy</a><br /></font>
          
        </div>
    </div>
  </div>

</body>
</html>